spring.application.name=session-09-logging

# 1. Qu?n lý Log Level (Best Practice là gi? INFO cho root và DEBUG cho code mình)
logging.level.root=INFO

# 2. Kích ho?t profile 'dev'
spring.profiles.active=prod