logging.level.com.re.session09=DEBUG

# Only check the Controller and Service that are malfunctioning; keep the INFO for other parts.
# -> Log TRACE should only be enabled for detailed error detection; after detection,
# it should be disabled to avoid excessive logging that can overload the system.
logging.level.com.re.session09.controller.OrderController=TRACE
logging.level.com.re.session09.service.impl.OrderServiceImpl=TRACE