logging.level.com.re.session09=DEBUG

# Ch? soi ?úng cái Controller, Service ?ang l?i, các ph?n khác v?n gi? INFO
# -> log TRACE ch? b?t ?? soi l?i chi ti?t, soi xong thì nên t?t ?i ?? tránh log nhi?u n?ng
logging.level.com.re.session09.controller.OrderController=TRACE
logging.level.com.re.session09.service.impl.OrderServiceImpl=TRACE