spring.application.name=session-09-logging

# 1. Manage Log Level
logging.level.root=INFO

# 2. Active environment:
# 2.1. dev + test (without JSON logs, include DEBUG logs)
# 2.2. prod (JSON logs, not include DEBUG logs)
#spring.profiles.active=dev
#spring.profiles.active=test
spring.profiles.active=prod