spring.application.name=session-09-logging

# 1. Qu?n lý Log Level (Best Practice là gi? INFO cho root và DEBUG cho code mình)
logging.level.root=INFO

# 2. Kích ho?t môi tr??ng:
# 2.1. dev + test (log không ph?i JSON)
# 2.2. prod (log d?ng JSON)
#spring.profiles.active=dev
#spring.profiles.active=test
spring.profiles.active=prod